version: '3.3'

services:

  app:
    container_name: file-agent
    image: file-agent-img
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:80'
# 如果想 runtime 修改個 ngixn.conf，un-comment 以下約行
#    volumes:
#      - file-agent:/etc/nginx/conf.d:rw
#
#volumes:
#  file-agent:
